version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  # backend:
  #   build: ./
  #   volumes:
  #     - /app
  #   ports:
  #     - "8000:8000"
  #   stdin_open: true
  #   tty: true
  #   command: sh -c "python manage.py runserver 0.0.0.0:8000"
  #   depends_on:
  #     - db

  frontend:
    build: ./client
    volumes:
      - /app/client
      # One-way volume to use node_modules from inside image
      - /app/client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: yarn start